-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Tyo CASCADE;
DROP TABLE IF EXISTS Tyokalu CASCADE;
DROP TABLE IF EXISTS Tyon_kohde CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS KayttajanTyot CASCADE;
